### ISSUE TITLE
Incompatibilities with "service_id" as a column name

### ISSUE THREAD

**Issue by mastfish** [fastly/fastly-rails#36]
At the moment, this gem isn't compatible with any rails application that has a table with a column named "service_id".

It throws 
```
ActiveRecord::DangerousAttributeError:
       service_id is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.
```

My application has a table with a column name of "service_id", so this is problematic.

**Comment by monfresh** [comment]
I'm running into the same issue. Any idea when this will be resolved? I would recommend renaming `service_id` to `customer_key`, since the Fastly web interface calls it `Customer ID`, not `Service ID`.

**Comment by monfresh** [comment]
Also, what is the purpose of defining these methods on the Model? If you don't need to override the global `service_id`, do you still need the Model methods?

And in what scenario would you need to override the global `service_id`? Is that common?

**Comment by set5think** [comment]
Hi,

Sorry for the delay in getting to this issue.  It's definitely something to resolve.  As a simple measure, we will rename this attribute to be much more unique.  That should remove the 99% of collision.

> since the Fastly web interface calls it Customer ID, not Service ID

The customer id and service id represent two separate things.  In the relational sense, a customer has many services.

> Also, what is the purpose of defining these methods on the Model? If you don't need to override the global service_id, do you still need the Model methods?

In order to perform surrogate-key purging, you need access to that particular Fastly service's unique identifier.  The particular concept of this plugin was to provide simple capabilities to allow easy edge caching and purging at the model level in Rails applications.  Depending on the purpose of your application and your usage of Fastly, you may want to be able map models to different Fastly services.  If you are interested in more information on this, definitely check out https://docs.fastly.com/, or get in touch with us, we'd be happy to help.

It's possible there's another implementation that could totally rid us of worrying about collision in any scenario, but it would probably take a bit more rethinking, and renaming seems a lot simpler and easy to resolve the issue at hand.

Thanks again for pointing this issue out.

**Comment by monfresh** [comment]
Thanks for the explanation, and the fix! I totally missed that the Customer ID and Service ID are different. Makes sense. Perhaps it would help to add a link to [this FAQ](https://docs.fastly.com/guides/faqs/where-can-i-find-my-service-id-customer-id-or-api-key) in this repo's Readme, and/or add a label for "Service ID" on the Fastly website to make it clearer.
